### ISSUE TITLE
senet154

### ISSUE THREAD

**Issue by shokan** [alimbekovKZ/lungs_segmentation_train#1]
`sh train.sh `
Unable to revert mtime: /Library/Fonts
Unable to revert mtime: /Library/Fonts/Microsoft
Fontconfig warning: ignoring UTF-8: not a valid region tag
Traceback (most recent call last):
  File "train.py", line 198, in <module>
    main()
  File "train.py", line 129, in main
    train_config = load_yaml(config_folder)
  File "/Users/shokan/Documents/1. Machine Learning/lungs_segmentation_train/utils/helpers.py", line 11, in load_yaml
    with open(file_name) as stream:
FileNotFoundError: [Errno 2] No such file or directory: 'experiments/senet154/train_config.yaml'

**Comment by DannyFGitHub** [comment]
Not sure where the senet154 folder is, it is meant to be in experiments.
However, I found I was able to move on by using any of the other models found in experiments.

For example, edit the train.sh to be:
```
python train.py experiments/resnet50/train_config.yaml
```

**Comment by alimbekovKZ** [comment]
There is no senet154 train_config.yaml and folder.
You can create your own or use configs from lungs_segmentation_train/tree/main/experiments
